Add gpu simulation support to client
SupertechLabs/general-superstaq pull request #124
Opened 2022-08-09 19:53 UTC by paaige

2022-08-23 21:25 UTC, vtomole requested changes
Need to pass the checks.

2022-08-23 21:25 UTC, vtomole commented on general_superstaq/typing.py
> +        "result": Optional[Counter],
Why are we adding this? Why can't we use `samples` here instead?

2022-08-25 14:35 UTC, vtomole reviewed
We need to add a `method` argument after https://github.com/SupertechLabs/SuperstaQ/pull/1500#pullrequestreview-1082958740

2022-08-25 15:36 UTC, vtomole approved these changes
LGTM

2022-08-25 15:37 UTC, merged

2022-08-25 15:39 UTC, vtomole reviewed
Wait. Is options a string or a dict? https://github.com/SupertechLabs/cirq-superstaq/pull/312/files#r955130631

2022-08-25 15:51 UTC, paaige commented
It's a JSON serialized dictionary (a string)